default: main.cpp standardIDLA.cpp optimizedIDLA.cpp standardTransformations.cpp util.cpp graphConstructors.cpp exampleSimulations.cpp visualization.cpp otherTransformations.cpp modifiedIDLA.cpp random.cpp
	g++ -std=c++11 -o sim main.cpp standardIDLA.cpp optimizedIDLA.cpp standardTransformations.cpp util.cpp graphConstructors.cpp exampleSimulations.cpp visualization.cpp otherTransformations.cpp modifiedIDLA.cpp random.cpp


